@baseUrl = http://localhost:3721

### Get all users
GET {{baseUrl}}/users
Accept: application/json

### Create a user
POST {{baseUrl}}/users
Content-Type: application/json
Accept: application/json

{
	"name": "Grace Hopper"
}
